declare module 'cytoscape-cola';
declare module 'cytoscape-dagre';
declare module 'cytoscape-undo-redo';
declare module 'cytoscape-expand-collapse';
declare module 'cytoscape-node-html-label';
declare module 'cytoscape-context-menus';
declare module 'cytoscape-popper';
declare module 'cytoscape-fcose';
declare module 'cytoscape-navigator';